### ISSUE TITLE
Make full-sky spectra agnostic to pixelization and/or add support for rectangular pixels 

### ISSUE THREAD

**Issue by msyriac** [damonge/NaMaster#22]
David, do you have an idea of how much work this would involve? It does look like key modules like `nmt_mask.c` are explicitly written for healpix pixels, at least in terms of function arguments. Would adapting these modules require converting logic that is hard-coded for healpix?

**Comment by damonge** [comment]
This is at the top of my list once the NaMaster paper is out.
I think the main roadblock would be to understand how libsharp uses other pixelization schemes. The rest should be relatively simple to rewrite, since only a few very specific functions make use of built-in healpix subroutines (e.g. the mask apodizers).
In the meantime you have the flat-sky version...

**Comment by damonge** [comment]
Moved to new repo
